### ISSUE TITLE
Make the buttons take up less space

### ISSUE THREAD

**Issue by AaronFried** [HurricanePete/Glider-Hunt-Client#6]
<img width="403" alt="screen shot 2018-03-22 at 9 29 36 pm" src="https://user-images.githubusercontent.com/17485691/37806791-38a457d2-2e18-11e8-9718-19342f00c667.png">

Can we center these a bit more and add some padding between them?

**Comment by HurricanePete** [comment]
Added margin to the bottom of the tiles for mobile, but they are already centered. Also set `display: none` for the decorative line between tiles on mobile.
